import { about, personalInfo } from "@/data/portfolio";

const siteUrl = "https://yalakanikhilreddy.dev";
export const ogLocale = "en_IN";

export const siteConfig = {
  siteUrl,
  homeUrl: `${siteUrl}/`,
  resumeUrl: `${siteUrl}${personalInfo.resumeUrl}`,
  updatedAt: "2026-05-03T00:00:00.000Z",
  siteName: "Yalaka Nikhil Reddy - Full-Stack Developer",
  title: `${personalInfo.name} — Full-Stack Web Developer`,
  description: personalInfo.tagline,
  author: personalInfo.name,
  creator: personalInfo.name,
  email: personalInfo.email,
  github: personalInfo.github,
  linkedin: personalInfo.linkedin,
  locale: "en-IN",
  ogLocale,
  ogImage: "/og-image.svg",
  keywords: [
    "Yalaka Nikhil Reddy",
    "Full-Stack Developer",
    "Web Developer",
    "MERN Stack",
    "Computer Science Student",
    "JavaScript Developer",
    "React Developer",
    "Node.js Developer",
    "MongoDB",
    "Express.js",
    "PHP Developer",
    "MySQL",
    "Java Developer",
    "Python Developer",
    "Frontend Development",
    "Backend Development",
    "Web Development",
    "REST APIs",
    "JWT Authentication",
    "Responsive Design",
    "Bug Tracking System",
    "Analytics Platform",
    "Car Rental System",
    "SIMATS",
    "Software Engineering",
    "Full Stack Web Application",
    "Database Design",
    "Version Control",
    "Git",
    "GitHub",
  ],
  geo: {
    region: "IN-TG",
    placename: "Kodad, Telangana, India",
    latitude: 17.3289,
    longitude: 78.8523,
    position: "17.3289;78.8523",
    icbm: "17.3289, 78.8523",
  },
  sameAs: [personalInfo.github, personalInfo.linkedin],
  aboutSummary: about.summary,
} as const;

export const canonicalPages = [siteConfig.homeUrl] as const;
